version: 2
updates:
- package-ecosystem: nuget
  directory: "/FormValidator"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.Http.Features
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: nunit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
